# -*- coding: utf-8 -*-
"""plswork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMFSUBxkFjzDNSBPgDefQ2QI3Fg8kZQA
"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

torch.manual_seed(123)

class FCN(nn.Module):
    def __init__(self, N_INPUT=2, N_OUTPUT=1, N_HIDDEN=32, N_LAYERS=3):
        super().__init__()
        self.act = nn.Tanh()
        self.input = nn.Linear(N_INPUT, N_HIDDEN)
        self.hidden = nn.ModuleList([nn.Linear(N_HIDDEN, N_HIDDEN) for _ in range(N_LAYERS - 1)])
        self.output = nn.Linear(N_HIDDEN, N_OUTPUT)

    def forward(self, x):
        h = self.act(self.input(x))
        for layer in self.hidden:
            h = self.act(layer(h))
        return self.output(h)

def solution(model, xy):
    x = xy[:, 0:1]
    y = xy[:, 1:2]
    steepness = 20.0
    # y=1 -> 1 (due to y term)
    # x=0 -> 0 (due to tanh(kx))
    # x=1 -> 0 (due to tanh(k(1-x)))
    boundary_term = y * torch.tanh(steepness * x) * torch.tanh(steepness * (1.0 - x))
    dist_function = x * (1.0 - x) * y * (1.0 - y)

    return boundary_term + dist_function * model(xy)
    
def sample_pde(N, eps=0.05):
    xy = torch.rand(N, 2, device=device)

    # Exempt corners from training to avoid high gradients
    mask = ~((xy[:,1] > 1 - eps) &((xy[:,0] < eps) | (xy[:,0] > 1 - eps)))
    xy = xy[mask]
    xy.requires_grad_(True)
    return xy

def plot_boundaries(model, epoch, current_loss):
    """Generates 4 subplots for boundaries + Shows Loss in Title"""

    s = torch.linspace(0, 1, 200, device=device).view(-1, 1)
    zeros = torch.zeros_like(s)
    ones = torch.ones_like(s)

    xy_top = torch.cat([s, ones], dim=1)      # y=1
    xy_bottom = torch.cat([s, zeros], dim=1)  # y=0
    xy_left = torch.cat([zeros, s], dim=1)    # x=0
    xy_right = torch.cat([ones, s], dim=1)    # x=1

    with torch.no_grad():
        u_top = solution(model, xy_top).cpu().numpy()
        u_bottom = solution(model, xy_bottom).cpu().numpy()
        u_left = solution(model, xy_left).cpu().numpy()
        u_right = solution(model, xy_right).cpu().numpy()

    s_np = s.cpu().numpy()

    fig, axs = plt.subplots(2, 2, figsize=(10, 6))

    loss_str = f"{current_loss:.3e}" if current_loss is not None else "Init"
    fig.suptitle(f'Epoch {epoch} | PDE Loss: {loss_str}', fontsize=16, fontweight='bold')

    # Top
    axs[0, 0].plot(s_np, u_top, 'r-', linewidth=2, label="Prediction")
    axs[0, 0].plot(s_np, np.ones_like(s_np), 'k--', alpha=0.3, label="Ideal (1.0)")
    axs[0, 0].set_title("Top Wall (y=1)")
    axs[0, 0].set_ylim(-0.1, 1.2)
    axs[0, 0].legend(loc='lower center', fontsize='small')
    axs[0, 0].grid(True, alpha=0.3)

    # Bottom
    axs[0, 1].plot(s_np, u_bottom, 'b-', linewidth=2)
    axs[0, 1].set_title("Bottom Wall (y=0)")
    axs[0, 1].set_ylim(-0.1, 0.2)
    axs[0, 1].grid(True, alpha=0.3)

    # Left
    axs[1, 0].plot(s_np, u_left, 'b-', linewidth=2)
    axs[1, 0].set_title("Left Wall (x=0)")
    axs[1, 0].set_ylim(-0.1, 0.2)
    axs[1, 0].grid(True, alpha=0.3)

    # Right
    axs[1, 1].plot(s_np, u_right, 'b-', linewidth=2)
    axs[1, 1].set_title("Right Wall (x=1)")
    axs[1, 1].set_ylim(-0.1, 0.2)
    axs[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()
    
model = FCN().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=5e-3)

def loss_fn():
    xy = sample_pde(4000)
    T = solution(model, xy)

    grads = torch.autograd.grad(T, xy, torch.ones_like(T), create_graph=True)[0]
    Tx, Ty = grads[:, 0:1], grads[:, 1:2]

    Txx = torch.autograd.grad(Tx, xy, torch.ones_like(Tx), create_graph=True)[0][:, 0:1]
    Tyy = torch.autograd.grad(Ty, xy, torch.ones_like(Ty), create_graph=True)[0][:, 1:2]

    return torch.mean((Txx + Tyy)**2)

epochs = 11000

print("Starting training...")
plot_boundaries(model, 0, None)

for epoch in range(1, epochs + 1):
    optimizer.zero_grad()
    loss = loss_fn()
    loss.backward()
    optimizer.step()

    # Print and Plot every 1000 epochs
    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d} | PDE Loss = {loss.item():.5e}")
        plot_boundaries(model, epoch, loss.item())

x = np.linspace(0, 1, 100)
y = np.linspace(0, 1, 100)
X, Y = np.meshgrid(x, y)
xy_plot = torch.tensor(np.stack([X.flatten(), Y.flatten()], axis=1), dtype=torch.float32, device=device)

with torch.no_grad():
    T_plot = solution(model, xy_plot).cpu().numpy().reshape(100, 100)

plt.figure(figsize=(6, 5))
cp = plt.contourf(X, Y, T_plot, 50, cmap="jet")
plt.colorbar(cp, label="Temperature")
plt.title(f"Final Solution (Loss: {loss.item():.2e})")
plt.show()
